// Copy the shared desktop UI (../ui/index.html) into the Android app, made
// safe for old Android WebViews. Produces two files; HelmServer picks one
// per request from the WebView's Chrome version:
//
//   assets/ui/index.html         Chrome 51+ (Android 7 and newer)
//   assets/ui/index-legacy.html  ES5 for Chrome 30-50 (Android 4.4 - 6),
//                                built by legacy.mjs
//
// The desktop app runs in current browsers, but its JavaScript uses
// async/await (Chrome 55), object spread (60), Object.entries (54) and
// NodeList.forEach (51) - any one of which would leave a blank or dead page
// on an older WebView.
//
// For the modern build this script:
//   1. downlevels every inline <script> with esbuild to TARGET
//   2. downlevels the inline <style> the same way (e.g. `inset`)
//   3. prepends small polyfills for the runtime APIs the UI relies on
//   4. VERIFIES the result: the JS must parse as plain ES2015, every
//      top-level function the HTML calls must still exist, and every inline
//      event handler must parse too. Any failure stops the build.
//
// Usage (from HelmAndroid/):  node tools/sync-ui.mjs

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { transformSync } from "esbuild";
import * as acorn from "acorn";
import { buildLegacy } from "./legacy.mjs";

// chrome51 is the floor: the UI uses destructuring inside for...of, which
// esbuild can't lower any further. It matches the WebView Android 7.0
// shipped with, and async/await (Chrome 55) still gets lowered to generators.
const TARGET = ["chrome51"];
const here = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(here, "../../ui/index.html");
const OUT = resolve(here, "../app/src/main/assets/ui/index.html");
const OUT_LEGACY = resolve(here, "../app/src/main/assets/ui/index-legacy.html");

const fail = (msg) => { console.error(`sync-ui: FAILED - ${msg}`); process.exit(1); };

const POLYFILLS = `
/* Helm for Android: polyfills for old WebViews (generated by tools/sync-ui.mjs) */
(function () {
  if (window.NodeList && !NodeList.prototype.forEach) NodeList.prototype.forEach = Array.prototype.forEach;
  if (window.HTMLCollection && !HTMLCollection.prototype.forEach) HTMLCollection.prototype.forEach = Array.prototype.forEach;
  if (!Object.entries) Object.entries = function (o) { return Object.keys(o).map(function (k) { return [k, o[k]]; }); };
  if (!Object.values) Object.values = function (o) { return Object.keys(o).map(function (k) { return o[k]; }); };
  if (!Array.prototype.includes) Object.defineProperty(Array.prototype, "includes", {
    value: function (v, from) { return this.indexOf(v, from) !== -1 || (v !== v && this.some(function (x) { return x !== x; })); }
  });
  if (!String.prototype.includes) String.prototype.includes = function (s, from) { return this.indexOf(s, from) !== -1; };
  if (window.Promise && !Promise.prototype.finally) Promise.prototype.finally = function (f) {
    return this.then(function (v) { return Promise.resolve(f()).then(function () { return v; }); },
                     function (e) { return Promise.resolve(f()).then(function () { throw e; }); });
  };
})();
`;

// ---------------------------------------------------------------------------

const html = readFileSync(SRC, "utf8");

// The Android server listens on this exact origin. If the UI ever changes it,
// the APK would load a UI that talks to nothing - fail the build instead.
if (!/const\s+API\s*=\s*['"]http:\/\/localhost:5001['"]/.test(html)) {
  fail("ui/index.html no longer declares `const API = 'http://localhost:5001'`; HelmServer.kt must match it");
}

// Names the original script defines at top level - inline onclick="..."
// handlers depend on these staying global after the transform.
const topLevelNames = (code, ecmaVersion) => {
  const names = new Set();
  for (const node of acorn.parse(code, { ecmaVersion, sourceType: "script" }).body) {
    if (node.type === "FunctionDeclaration") names.add(node.id.name);
    if (node.type === "VariableDeclaration")
      for (const d of node.declarations) if (d.id.type === "Identifier") names.add(d.id.name);
  }
  return names;
};

let scripts = 0;
const handlerSources = [];

let out = html.replace(/<script(\s[^>]*)?>([\s\S]*?)<\/script>/g, (whole, attrs = "", code) => {
  if (/\bsrc\s*=/.test(attrs) || (/\btype\s*=/.test(attrs) && !/javascript|module/.test(attrs))) return whole;
  scripts++;

  let lowered;
  try {
    lowered = transformSync(code, { loader: "js", target: TARGET, charset: "utf8", legalComments: "inline" }).code;
  } catch (e) {
    fail(`esbuild could not downlevel script #${scripts} to ${TARGET}: ${e.message}`);
  }

  // Must be plain ES2015: no async/await, no object spread, no ** etc.
  try {
    acorn.parse(lowered, { ecmaVersion: 2015, sourceType: "script" });
  } catch (e) {
    fail(`script #${scripts} still contains syntax newer than ES2015 after downleveling: ${e.message}`);
  }

  const before = topLevelNames(code, "latest");
  const after = topLevelNames(lowered, 2015);
  const lost = [...before].filter((n) => !after.has(n));
  if (lost.length) fail(`top-level names lost in script #${scripts}: ${lost.join(", ")}`);

  // Event handlers built inside JS strings, e.g. onclick="x('${p}')". Read
  // them from the ORIGINAL source: esbuild may rewrite templates as
  // "".concat(...), which splits the handler text across string pieces.
  for (const m of code.matchAll(/\bon[a-z]+="([^"]*)"/g)) handlerSources.push(m[1]);

  return `<script${attrs}>${lowered}</script>`;
});

if (scripts === 0) fail("no inline <script> found in ui/index.html");

out = out.replace(/<style(\s[^>]*)?>([\s\S]*?)<\/style>/g, (whole, attrs = "", css) => {
  try {
    return `<style${attrs}>${transformSync(css, { loader: "css", target: TARGET }).code}</style>`;
  } catch (e) {
    fail(`esbuild could not process <style>: ${e.message}`);
  }
});

// Inline handlers written directly in the HTML markup.
for (const m of html.replace(/<script[\s\S]*?<\/script>/g, "").matchAll(/\bon[a-z]+="([^"]*)"/g)) handlerSources.push(m[1]);

// esbuild never sees handler attributes, so they run exactly as written.
// They're often assembled from nested templates, which a parser can't check
// in isolation - so scan them for the syntax an old WebView can't run.
// (Arrow functions, let/const and template literals are fine in Chrome 51.)
const TOO_NEW = [
  [/\?\./, "optional chaining ?."], [/\?\?/, "nullish coalescing ??"],
  [/\basync\b/, "async"], [/\bawait\b/, "await"], [/\*\*/, "exponent **"],
  [/\{\s*\.\.\./, "object spread {...}"], [/(\|\||&&|\?\?)=/, "logical assignment"],
];
for (const h of handlerSources) {
  const hit = TOO_NEW.find(([re]) => re.test(h));
  if (hit) fail(`inline event handler uses ${hit[1]}, which an old WebView can't run: ${JSON.stringify(h)}`);
}

// Polyfills go first in <head> so they exist before any app code runs.
if (!/<head[^>]*>/i.test(out)) fail("no <head> in ui/index.html");
out = out.replace(/<head[^>]*>/i, (h) => `${h}\n<script>${POLYFILLS}</script>`);
out = `<!-- GENERATED by HelmAndroid/tools/sync-ui.mjs from ui/index.html - edit that file, not this one -->\n${out}`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, out);

console.log(`sync-ui: ok - ${scripts} script block(s) downleveled to ${TARGET.join(",")}, `
  + `${handlerSources.length} inline handlers checked, ES2015 parse verified`);
console.log(`sync-ui: wrote ${OUT} (${out.length.toLocaleString()} bytes)`);

// ---- legacy (ES5) build for Android 4.4 - 6 ------------------------------
// Inline handlers run as written, so for Chromium 30 they must be plain ES5.
// Handlers assembled in JS templates contain ${...} expressions; those are JS
// code that Babel converts. Only the literal text around them runs as-is.
const stripInterpolations = (h) => {
  let out = "";
  for (let i = 0; i < h.length; i++) {
    if (h[i] === "$" && h[i + 1] === "{") {
      let depth = 1, j = i + 2;
      while (j < h.length && depth > 0) { if (h[j] === "{") depth++; else if (h[j] === "}") depth--; j++; }
      out += "x"; i = j - 1;
    } else out += h[i];
  }
  return out;
};
const ES6_IN_HANDLER = [[/=>/, "arrow function"], [/`/, "template literal"], [/\b(let|const)\s/, "let/const"], ...TOO_NEW];
for (const raw of handlerSources) {
  const h = stripInterpolations(raw);
  const hit = ES6_IN_HANDLER.find(([re]) => re.test(h));
  if (hit) fail(`inline event handler uses ${hit[1]}, which Android 4.4's WebView can't run: ${JSON.stringify(raw)}`);
}
const legacy = buildLegacy(html, { fail });
const legacyOut = `<!-- GENERATED by HelmAndroid/tools/sync-ui.mjs (legacy ES5 build) from ui/index.html - edit that file, not this one -->\n${legacy.html}`;
writeFileSync(OUT_LEGACY, legacyOut);
const st = legacy.stats;
console.log(`sync-ui: ok - legacy ES5 build verified: ${st.polyfills} polyfills (${Math.round(st.polyfillBytes / 1024)} KB), `
  + `${st.themedRules} themed CSS values, ${st.varRewrites} var() strings rerouted`);
console.log(`sync-ui: wrote ${OUT_LEGACY} (${legacyOut.length.toLocaleString()} bytes)`);
