#!/usr/bin/env bash
# Refuse to publish an APK that isn't what we think it is.
#
# Every failed check is reported as a GitHub Actions ::error annotation (so
# the reason shows on the run page without digging through logs), and a
# ::notice summarises what was published.
#
# Usage: tools/verify-apk.sh <path/to/Helm.apk> <build-tools-dir>
set -u

APK="$1"
BT="$2"
# Helm's release certificate (see HelmAndroid/README.md). Lowercase, no colons.
RELEASE_CERT="7ffe3d03df521e99a40613173309e6cbe6c6c06848a4b5b79f3e179d0ede892e"
MIN_SDK="19"

fail=0
ok()  { echo "ok:     $1"; }
bad() { echo "::error title=APK check failed::$1"; fail=1; }

work="$(mktemp -d)"; trap 'rm -rf "$work"' EXIT

if ! "$BT/apksigner" verify --verbose --print-certs "$APK" > "$work/verify.txt" 2>&1; then
  bad "apksigner rejected the APK: $(tr '\n' ' ' < "$work/verify.txt" | cut -c1-400)"
  exit 1
fi
if ! "$BT/aapt2" dump badging "$APK" > "$work/badging.txt" 2>&1; then
  bad "aapt2 could not read the APK: $(head -c 400 "$work/badging.txt")"
  exit 1
fi
cat "$work/verify.txt"
grep -E "^package:|dkVersion|native-code" "$work/badging.txt"

# v1 (JAR) signing is what Android 5 and 6 check; v2 is what 7+ checks.
grep -qiE "v1 scheme \(JAR signing\): *true" "$work/verify.txt" \
  && ok "v1 signature (Android 5-6)" || bad "no v1 (JAR) signature: won't install below Android 7"
grep -qiE "v2 scheme \(APK Signature Scheme v2\): *true" "$work/verify.txt" \
  && ok "v2 signature (Android 7+)" || bad "no v2 signature"

grep -qi "certificate SHA-256 digest: $RELEASE_CERT" "$work/verify.txt" \
  && ok "signed with Helm's release key" \
  || bad "not signed with Helm's release key (got: $(grep -i -m1 'SHA-256 digest' "$work/verify.txt" | sed 's/.*digest: //'))"

# aapt2 prints minSdkVersion:'21'; the older aapt printed sdkVersion:'21'.
grep -qiE "^(min)?sdkVersion:'$MIN_SDK'" "$work/badging.txt" \
  && ok "minSdk $MIN_SDK" || bad "minSdk is not $MIN_SDK: $(grep -iE '^(min)?sdkVersion' "$work/badging.txt" | head -1)"

unzip -l "$APK" > "$work/list.txt"
for abi in armeabi-v7a arm64-v8a; do
  grep -q "lib/$abi/libadb.so" "$work/list.txt" \
    && ok "adb bundled for $abi" || bad "lib/$abi/libadb.so missing from the APK"
done

for page in index.html index-legacy.html; do
  unzip -p "$APK" "assets/ui/$page" > "$work/ui.html" 2>/dev/null
  head -c 300 "$work/ui.html" | grep -q "GENERATED by HelmAndroid/tools/sync-ui.mjs" \
    && ok "UI bundled: $page" || bad "assets/ui/$page is missing or wasn't produced by sync-ui.mjs"
done
# Android 4.4 downloads depend on Conscrypt's native TLS library.
grep -q "lib/armeabi-v7a/libconscrypt_jni.so" "$work/list.txt" \
  && ok "Conscrypt TLS bundled (Android 4.4 downloads)" || bad "Conscrypt native library missing for armeabi-v7a"

sha="$(sha256sum "$APK" | cut -d' ' -f1)"
pkg="$(grep -m1 '^package:' "$work/badging.txt" | sed -E "s/.*versionName='([^']*)'.*/\1/")"
size="$(( $(stat -c%s "$APK") / 1024 ))"
if [ "$fail" -eq 0 ]; then
  echo "::notice title=Helm.apk verified::version $pkg, ${size} KB, minSdk $MIN_SDK, release-signed, sha256 $sha"
fi
exit "$fail"
